version: '3.4'

services:
  vacation:
    image: vacation
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    command: ["http-server", "dist"]
